//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_cost
    {
        public int Id { get; set; }
        public int BookingId { get; set; }
        public int ServicesAndPartsId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int Qtd { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual ServicesAndParts ServicesAndParts { get; set; }
    }
}
