//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bookings()
        {
            this.booking_cost = new HashSet<booking_cost>();
        }
    
        public int Id { get; set; }
        public string Make { get; set; }
        public int BookingTypeId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public int StatusId { get; set; }
        public int CustomerId { get; set; }
        public string Observation { get; set; }
        public string VRC { get; set; }
        public string VLC { get; set; }
        public int EngineTypeId { get; set; }
        public int VehicleTypeId { get; set; }
        public string Licence { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<decimal> BasicCost { get; set; }
    
        public virtual BookingTypes BookingTypes { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual Status Status { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_cost> booking_cost { get; set; }
    }
}
