//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarageManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GarageManagementEntities : DbContext
    {
        public GarageManagementEntities()
            : base("name=GarageManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Makes> Makes { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<VehicleType> VehicleType { get; set; }
        public virtual DbSet<BookingTypes> BookingTypes { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<EngineType> EngineType { get; set; }
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<ServicesAndParts> ServicesAndParts { get; set; }
        public virtual DbSet<booking_cost> booking_cost { get; set; }
    }
}
